name: CI for Preview Branches
on:
  push:
    branches-ignore: ['main', 'staging', 'preview-**']
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  checks:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
