name: Fly Deploy Movex (Staging)
on:
  pull_request:
    branches: ['staging', 'add-github-actions']
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  deploy:
    name: Build & Deploy
    needs: [ci]
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: yarn install
      - run: yarn build-movex-chessroulette
      - run: flyctl deploy -c ./fly.movex-staging.toml --dockerfile ./Dockerfile.movex --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
